# Generated by Django 2.2 on 2021-06-19 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wish_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='granted_wishes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='pending_wishes',
            field=models.IntegerField(default=0),
        ),
    ]
