# Generated by Django 2.2 on 2021-06-19 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wish_app', '0002_auto_20210619_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish',
            name='wished_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishes', to='wish_app.User'),
        ),
    ]
